apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant-deployment
spec:
  selector:
    matchLabels:
      app: homeassistant
  replicas: 1
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: nfs-volume
          nfs: 
            server: 10.0.100.100
            path: /var/nfs/general/homeassistant
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant
        volumeMounts:
          - name: nfs-volume
            mountPath: /config
        ports:
        - containerPort: 8123

---
apiVersion: v1
kind: Service
metadata:
  name: srv-homeassistant
spec:
  type: NodePort
  selector:
    app: homeassistant
  ports:
    - protocol: TCP
      port: 8123
      nodePort: 30085
