apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-deployment
spec:
  selector:
    matchLabels:
      app: jupyter
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      # securityContext:
      #   runAsUser: 1000
      #   runAsGroup: 1000
      # volumes:
      #   - name: nfs-volume
      #     nfs: 
      #       server: 10.0.100.100
      #       path: /var/nfs/general/homeassistant
      containers:
      - name: jupyter
        image: jupyter/scipy-notebook
        # volumeMounts:
        #   - name: nfs-volume
        #     mountPath: /config
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: srv-jupyter
spec:
  type: NodePort
  selector:
    app: jupyter
  ports:
    - protocol: TCP
      port: 8888
      nodePort: 30088
