apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
spec:
  selector:
    matchLabels:
      app: plex
  replicas: 1
  template:
    metadata:
      labels:
        app: plex
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      # volumes:
      #   - name: nfs-volume
      #     nfs: 
      #       server: 10.0.100.100
      #       path: /var/nfs/general/homeassistant
      containers:
      - name: plex
        image: linuxserver/plex
        # volumeMounts:
        #   - name: nfs-volume
        #     mountPath: /config
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: srv-plex
spec:
  type: NodePort
  selector:
    app: plex
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30086
