apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
        - name: nfs-volume
          nfs: 
            server: 10.0.100.100
            path: /var/nfs/general/jenkins
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk11
        volumeMounts:
          - name: nfs-volume
            mountPath: /var/jenkins_home
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: srv-jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30082
