# kubectl run --rm -i --tty busybox --image=itsthenetwork/nfs-server-alpine:latest --restart=Never --overrides='{"spec": {"template": {"spec": {"containers": [{"securityContext": {"privileged": true} }]}}}}'

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  selector:
    matchLabels:
      app: nfs-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:latest
          # env:
          # - name: SHARED_DIRECTORY
          #   value: /nfs
          # - name: PERMITTED
          #   value: "10.*"
          securityContext:
            privileged: true