apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx01-deployment
spec:
  selector:
    matchLabels:
      app: nginx01
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx01
    spec:
      containers:
      - name: nginx01
        image: nginx:latest
        ports:
        - containerPort: 80
          # name: nginx01-port

---
apiVersion: v1
kind: Service
metadata:
  name: srv-nginx01
spec:
  type: NodePort
  selector:
    app: nginx01
  ports:
    - protocol: TCP
      port: 80
      # targetPort: nginx01-port
      nodePort: 30081
