apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: nginx
        image: ydeal/springboot-helloworld:0.2
        ports:
        - containerPort: 8080
          name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: srv-http
spec:
  type: NodePort
  selector:
    app: springboot
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-web-svc
      nodePort: 30080
      