name: Oracle cloud deployment
on:
  push:
    # branches:
    #   - master
    # paths:
    #   - infra/**
  workflow_dispatch: 
jobs:
  Infra:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TF_VAR_tenancy_ocid: ${{ secrets.TF_VAR_tenancy_ocid }}
      TF_VAR_user_ocid: ${{ secrets.TF_VAR_user_ocid }}
      TF_VAR_fingerprint: ${{ secrets.TF_VAR_fingerprint }}
      TF_VAR_backend_address: ${{ secrets.TF_VAR_backend_address }}
      TF_VAR_private_key_path: "~/.oci/oracle_api_key_for_gitAction.pem"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Show TF version
      #   run: |
      #     terraform --version

      - name: 'Install OCI CLI'
        run: |
          mkdir ~/.oci
          mkdir ~/.aws
          echo "${{ secrets.ORACLE_CONFIG_FOR_GITACTION }}" > ~/.oci/config
          echo "${{ secrets.ORACLE_API_KEY_FOR_GITACTION_PEM }}" > ~/.oci/oracle_api_key_for_gitAction.pem
          echo "${{ secrets.ORACLE_BACKEND_AWS_CREDENTIALS }}" > ~/.aws/credentials
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          echo "/home/runner/bin" >> $GITHUB_PATH
          exec -l $SHELL
          oci setup repair-file-permissions --file /home/runner/.oci/config
          oci setup repair-file-permissions --file /home/runner/.oci/key.pem

      - name: 'Install kubectl'
        run: |
          mkdir /tmp/.kube
          curl -L -O "https://dl.k8s.io/release/v1.22.4/bin/linux/amd64/kubectl" -o kubectl
          chmod +x kubectl
          mv kubectl /usr/local/bin
          mkdir ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.oci/*
          chmod 600 ~/.kube/*
          chmod 600 ~/.aws/*

      # - name: 'Currently running services'
      #   run: kubectl get pods -A

      - name: service_Init
        run: make serviceInit

      - name: Infra_Deploy
        run: make serviceDeploy

      - name: tmate
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
